# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_oscilokopio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetOscilokopio(object):
    def setupUi(self, WidgetOscilokopio):
        WidgetOscilokopio.setObjectName("WidgetOscilokopio")
        WidgetOscilokopio.resize(846, 525)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetOscilokopio.sizePolicy().hasHeightForWidth())
        WidgetOscilokopio.setSizePolicy(sizePolicy)
        WidgetOscilokopio.setMinimumSize(QtCore.QSize(0, 0))

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(WidgetOscilokopio)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        # --- WIDGET PLOT ---
        self.widget_plot = QtWidgets.QWidget(WidgetOscilokopio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.widget_plot.setSizePolicy(sizePolicy)
        self.widget_plot.setMinimumSize(QtCore.QSize(491, 391))
        self.widget_plot.setObjectName("widget_plot")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_plot)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.plot = QtWidgets.QFrame(self.widget_plot)
        self.plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot.setObjectName("plot")

        self.horizontalLayout.addWidget(self.plot)
        self.horizontalLayout_3.addWidget(self.widget_plot)

        # --- WIDGET CONTROLES ---
        self.widget_controles = QtWidgets.QWidget(WidgetOscilokopio)
        self.widget_controles.setSizePolicy(sizePolicy)
        self.widget_controles.setMinimumSize(QtCore.QSize(321, 411))
        self.widget_controles.setFont(QtGui.QFont())
        self.widget_controles.setObjectName("widget_controles")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_controles)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # --- WIDGET EJES ---
        self.widget_ejes = QtWidgets.QWidget(self.widget_controles)
        self.widget_ejes.setObjectName("widget_ejes")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_ejes)
        self.verticalLayout.setObjectName("verticalLayout")

        # --- EJE HORIZONTAL ---
        self.horizontal = QtWidgets.QGroupBox(self.widget_ejes)
        self.horizontal.setObjectName("horizontal")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.lineEdit = QtWidgets.QLineEdit(self.horizontal)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)

        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.horizontal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_3.addWidget(self.doubleSpinBox)

        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)

        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.horizontal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(0.0)
        self.doubleSpinBox_2.setValue(0.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_2)

        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)

        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.horizontal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(0.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_3)

        self.verticalLayout.addWidget(self.horizontal)

        # --- EJE VERTICAL ---
        self.vertical_2 = QtWidgets.QGroupBox(self.widget_ejes)
        self.vertical_2.setObjectName("vertical_2")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.vertical_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.verticalLayout.addWidget(self.vertical_2)
        self.horizontalLayout_2.addWidget(self.widget_ejes)

        # --- WIDGET LECTURA ---
        self.widget_lectura = QtWidgets.QWidget(self.widget_controles)
        self.widget_lectura.setObjectName("widget_lectura")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_lectura)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.lectura = QtWidgets.QGroupBox(self.widget_lectura)
        self.lectura.setObjectName("lectura")
        self.verticalLayout_2.addWidget(self.lectura)

        self.trigger = QtWidgets.QGroupBox(self.widget_lectura)
        self.trigger.setObjectName("trigger")
        self.verticalLayout_2.addWidget(self.trigger)

        self.math = QtWidgets.QGroupBox(self.widget_lectura)
        self.math.setObjectName("math")
        self.verticalLayout_2.addWidget(self.math)

        self.horizontalLayout_2.addWidget(self.widget_lectura)
        self.horizontalLayout_3.addWidget(self.widget_controles)

        self.retranslateUi(WidgetOscilokopio)
        QtCore.QMetaObject.connectSlotsByName(WidgetOscilokopio)

    def retranslateUi(self, WidgetOscilokopio):
        _translate = QtCore.QCoreApplication.translate
        WidgetOscilokopio.setWindowTitle(_translate("WidgetOscilokopio", "WidgetOscilokopio"))
        self.horizontal.setTitle(_translate("WidgetOscilokopio", "Eje horizontal"))
        self.lineEdit.setText(_translate("WidgetOscilokopio", "EJE HORIZONTAL"))
        self.lineEdit_3.setText(_translate("WidgetOscilokopio", "Segundos/División"))
        self.lineEdit_4.setText(_translate("WidgetOscilokopio", "Posición"))
        self.lineEdit_5.setText(_translate("WidgetOscilokopio", "Entrada"))
        self.vertical_2.setTitle(_translate("WidgetOscilokopio", "Eje vertical"))
        self.lineEdit_2.setText(_translate("WidgetOscilokopio", "EJE VERTICAL"))
        self.lectura.setTitle(_translate("WidgetOscilokopio", "Lectura"))
        self.trigger.setTitle(_translate("WidgetOscilokopio", "Trigger"))
        self.math.setTitle(_translate("WidgetOscilokopio", "Math"))
